spring.application.name=proyectoBases
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=proyecto_bases1
spring.jpa.properties.hibernate.default_schema=proyecto_bases1
spring.datasource.username=postgres
spring.datasource.password=lulito
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.data-locations=classpath:import.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
